### ISSUE TITLE
Generate ASS with rubies on words

### ISSUE THREAD

**Issue by zhxie** [zhxie/anioke#75]
Currently, we can generate ASS whether it consists of all original words or all rubies. But we want to generate ASS with rubies on words, like furiganas to kanjis.

We have to come up with a new ASS generation method to solve the issue.

- [ ] Generate ASS with rubies
- [x] Generate rubies in JOYSOUND lyrics provider

**Comment by maoqxxmm** [comment]
![image](https://user-images.githubusercontent.com/18388484/186581313-f28a4f0e-36d2-4ac5-a4b2-40af0cd1efcf.png)

Demo has been completed. It will be added to Anioke soon.
